blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/ChE-Toolbox/che-toolbox/discussions
    about: For general discussions, ideas, or help from the community
  - name: Documentation
    url: https://github.com/ChE-Toolbox/che-toolbox/tree/main/docs
    about: Read the documentation for guides and tutorials
